#:kivy 1.0.9
<CoinTossBoxLayout>:
    orientation:'vertical'

    Label:
        text:'welcome to head or tials'
        font_size:50

    BoxLayout:
        orientation:'horizontal'
        Button:
            text:'Heads'
            on_release: root.choice('Heads')

        Button:
            text:'Tails'
            on_release:root.choice('Tails')

    Label:
    id:result
    font_size:40
    text:''
